import { emptySection, generateId } from './utils.ts'
import type { Template } from './templates.ts'

export const conversationTemplates: Template[] = [
  {
    name: 'At the Café',
    description: 'Ordering drinks and chatting',
    category: 'conversation',
    build: () => [
      {
        ...emptySection(), id: generateId(),
        title: 'Ali',
        sentence: 'Hello! Can I have a coffee, please?',
        translation: 'مرحباً! هل يمكنني الحصول على قهوة، من فضلك؟',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Sara',
        gender: 'female',
        sentence: 'Sure! Would you like anything else?',
        translation: 'بالتأكيد! هل ترغب في أي شيء آخر؟',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Ali',
        sentence: 'Yes, a croissant too, please.',
        translation: 'نعم، وكرواسون أيضاً، من فضلك.',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Sara',
        gender: 'female',
        sentence: 'That will be 5 dollars. Here you go.',
        translation: 'سيكون 5 دولارات. تفضل.',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Ali',
        sentence: 'Thank you so much!',
        translation: 'شكراً جزيلاً!',
        words: [],
      },
    ],
  },
  {
    name: 'First Meeting',
    description: 'Introducing yourself to someone',
    category: 'conversation',
    build: () => [
      {
        ...emptySection(), id: generateId(),
        title: 'Ahmed',
        sentence: 'Hi! My name is Ahmed. What is your name?',
        translation: 'مرحباً! اسمي أحمد. ما اسمك؟',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Lisa',
        gender: 'female',
        sentence: 'Nice to meet you, Ahmed! I am Lisa.',
        translation: 'تشرفنا يا أحمد! أنا ليزا.',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Ahmed',
        sentence: 'Where are you from, Lisa?',
        translation: 'من أين أنت يا ليزا؟',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Lisa',
        gender: 'female',
        sentence: 'I am from Canada. And you?',
        translation: 'أنا من كندا. وأنت؟',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Ahmed',
        sentence: 'I am from Egypt. Welcome!',
        translation: 'أنا من مصر. أهلاً بك!',
        words: [],
      },
    ],
  },
  {
    name: 'Asking for Directions',
    description: 'Finding your way around the city',
    category: 'conversation',
    build: () => [
      {
        ...emptySection(), id: generateId(),
        title: 'Tourist',
        sentence: 'Excuse me, where is the nearest hospital?',
        translation: 'عذراً، أين أقرب مستشفى؟',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Local',
        sentence: 'Go straight and turn left at the traffic light.',
        translation: 'اذهب مباشرة ثم انعطف يساراً عند إشارة المرور.',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Tourist',
        sentence: 'Is it far from here?',
        translation: 'هل هو بعيد من هنا؟',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Local',
        sentence: 'No, it is about 5 minutes on foot.',
        translation: 'لا، حوالي 5 دقائق سيراً على الأقدام.',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Tourist',
        sentence: 'Thank you very much for your help!',
        translation: 'شكراً جزيلاً على مساعدتك!',
        words: [],
      },
    ],
  },
  {
    name: 'At the Restaurant',
    description: 'Ordering food with a friend',
    category: 'conversation',
    build: () => [
      {
        ...emptySection(), id: generateId(),
        title: 'Waiter',
        sentence: 'Good evening! Are you ready to order?',
        translation: 'مساء الخير! هل أنتم مستعدون لطلب الطعام؟',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Customer',
        sentence: 'Yes, I would like the grilled chicken, please.',
        translation: 'نعم، أودّ الدجاج المشوي، من فضلك.',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Waiter',
        sentence: 'Excellent choice! Would you like a drink with that?',
        translation: 'اختيار ممتاز! هل ترغب في مشروب معه؟',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Customer',
        sentence: 'Yes, a glass of orange juice, please.',
        translation: 'نعم، كوب من عصير البرتقال، من فضلك.',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Waiter',
        sentence: 'I will bring it right away.',
        translation: 'سأحضره لك فوراً.',
        words: [],
      },
    ],
  },
  {
    name: 'At the Hotel',
    description: 'Checking in and asking about services',
    category: 'conversation',
    build: () => [
      {
        ...emptySection(), id: generateId(),
        title: 'Guest',
        sentence: 'Hello, I have a reservation under the name Omar.',
        translation: 'مرحباً، لدي حجز باسم عمر.',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Receptionist',
        gender: 'female',
        sentence: 'Welcome, Mr. Omar! Let me check your reservation.',
        translation: 'أهلاً بك يا سيد عمر! دعوني أتحقق من حجزك.',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Guest',
        sentence: 'What time is breakfast served?',
        translation: 'في أي وقت يُقدّم الإفطار؟',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Receptionist',
        gender: 'female',
        sentence: 'Breakfast is from 7 to 10 in the morning.',
        translation: 'الإفطار من الساعة 7 إلى 10 صباحاً.',
        words: [],
      },
      {
        ...emptySection(), id: generateId(),
        title: 'Guest',
        sentence: 'Perfect. Thank you!',
        translation: 'ممتاز. شكراً لك!',
        words: [],
      },
    ],
  },
]
